from config_snowflake import SnowflakeConnector
from snowflake.connector.pandas_tools import write_pandas
import pandas as pd
import re

snowflake_conn = SnowflakeConnector()
conn = snowflake_conn.connect()
conn.cursor().execute("USE EMPRESAS.DB_EMPRESAS;")
conn.cursor().execute("""
CREATE OR REPLACE VIEW EMPRESAS.DB_EMPRESAS.DF_PROCESSOS_JUDICIAIS AS
SELECT
    A.CNPJ,
    A.AREA,
    A.COMARCA,
    A.JULGAMENTO,
    A.DATADECISAO,
    A.UF,
    A.TRIBUNAL,
    A.CITACAOTIPO,
    A.VALORCAUSA,
    A.VALORPREDICAOCONDENACAO,
    B.DT_ABERTURA,
    B.DE_CNAE_PRINCIPAL,
    B.DE_RAMO_ATIVIDADE,
    B.DE_SETOR,
    B.ENDERECO_UF,
    B.ENDERECO_MESORREGIAO,
    B.SITUACAO_CADASTRAL,
    C.NIVEL_ATIVIDADE,
    D.EMPRESA_PORTE,
    E.SAUDE_TRIBUTARIA,
    F.OPTANTE_SIMPLES,
    F.OPTANTE_SIMEI
FROM EMPRESAS.DB_EMPRESAS.EMPRESAS_PROCESSOS_JUDICIAIS A
LEFT JOIN EMPRESAS.DB_EMPRESAS.DF_EMPRESAS B ON B.CNPJ = A.CNPJ  
LEFT JOIN EMPRESAS.DB_EMPRESAS.EMPRESAS_NIVEL_ATIVIDADE C ON C.CNPJ = A.CNPJ
LEFT JOIN EMPRESAS.DB_EMPRESAS.EMPRESAS_PORTE D ON D.CNPJ = A.CNPJ
LEFT JOIN EMPRESAS.DB_EMPRESAS.EMPRESAS_SAUDE_TRIBUTARIA E ON E.CNPJ = A.CNPJ
LEFT JOIN EMPRESAS.DB_EMPRESAS.EMPRESAS_SIMPLES F ON F.CNPJ = A.CNPJ;
""")

snowflake_conn.close_connection()