{{ config(materialized='view') }}

WITH nivel_atividade AS (
    SELECT  * 
    FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_NIVEL_ATIVIDADE),
porte AS(  
    SELECT  * 
    FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_PORTE),
contagem_processos AS(
    SELECT F.CNPJ
    ,F.AREA
    ,COUNT(F.CNPJ) AS TOTAL_AREA
    ,(SELECT COUNT(*) FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_PROCESSOS_JUDICIAIS X WHERE F.CNPJ=X.CNPJ) AS TOTAL_GERAL 
    FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_PROCESSOS_JUDICIAIS F
    GROUP BY F.CNPJ,F.AREA),
saude_tributaria as(
    SELECT * 
    FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_SAUDE_TRIBUTARIA),
simples as (
    SELECT CNPJ
    ,(CASE WHEN OPTANTE_SIMEI ='true' then 'SIM' else 'NÃO' END) AS OPTANTE_SIMEI
    ,(CASE WHEN OPTANTE_SIMPLES='true' then 'SIM' else 'NÃO' END) AS OPTANTE_SIMPLES
FROM PROJETO_NEOWAY.PUBLIC.EMPRESAS_SIMPLES)


SELECT A.CNPJ
,A.DT_ABERTURA
,A.DE_CNAE_PRINCIPAL
,A.DE_RAMO_ATIVIDADE
,A.DE_SETOR
,A.ENDERECO_MUNICIPIO
,A.ENDERECO_UF
,A.ENDERECO_REGIAO
,A.ENDERECO_MESORREGIAO
,A.SITUACAO_CADASTRAL
,C.EMPRESA_PORTE
,IFNULL(MIN(E.TOTAL_GERAL),0) CONTAGEM_PROCESSOS
,F.SAUDE_TRIBUTARIA
,G.OPTANTE_SIMPLES
,G.OPTANTE_SIMEI
 FROM PROJETO_NEOWAY.PUBLIC.DF_EMPRESAS A
LEFT JOIN nivel_atividade B on B.CNPJ=A.CNPJ
LEFT JOIN porte C on A.CNPJ=C.CNPJ
LEFT JOIN contagem_processos E ON A.CNPJ=E.CNPJ
LEFT JOIN saude_tributaria F ON A.CNPJ=F.CNPJ
LEFT JOIN simples G ON A.CNPJ=G.CNPJ
GROUP BY
A.CNPJ
,A.DT_ABERTURA
,A.DE_CNAE_PRINCIPAL
,A.DE_RAMO_ATIVIDADE
,A.DE_SETOR
,A.ENDERECO_MUNICIPIO
,A.ENDERECO_UF
,A.ENDERECO_REGIAO
,A.ENDERECO_MESORREGIAO
,C.EMPRESA_PORTE
,F.SAUDE_TRIBUTARIA
,G.OPTANTE_SIMPLES
,G.OPTANTE_SIMEI
,A.SITUACAO_CADASTRAL



